### ISSUE TITLE
Timers runs slower when app is launched or backgrounded

### ISSUE THREAD

**Issue by ThiagoVinicius** [smallstoneapps/multi-timer#16]
The clock drifts a bit every time the app is backgrounded then subsequently launched. This is more noticeable on long running timers, but it can be reproduced on short timers, following these steps:
###### Steps to reproduce
1. Set a 1 minute timer in multi-timer;
2. Set a 1 minute timer on another app (computer, phone, etc.);
3. Start both timers at the same time;
4. Press back, exiting to a multi-timer;
5. Lauch multi-timer;
6. repeat from step 4.
###### Expected behaviour

Both timers should end by the 1 minute mark.
###### Observed behaviour

Multi-timer's timer ends later that the minute mark.

**Comment by protist** [comment]
I'm just wondering if it's known how out the timer can be. This is potentially quite an important issue for me.

**Comment by protist** [comment]
I tested this once, with a one minute timer, exiting and re-launching multi-timer ~8 times. The timer was out by ~4 seconds, i.e. ~7%. I also tested exiting once, with no re-launch (for both one minute and one hour). There was no noticeable delay (with the precision available to me).
